### ISSUE TITLE
道理我都懂，啥时候出iOS版本？

### ISSUE THREAD

**Issue by delayhsiao** [zhaoyang21cn/IMTUIkit_android#1]
好看是挺好看的 扩展性怎么样？

**Comment by zhaoyang21cn** [comment]
ios版本正在测试中，这周或者下周就可以发布了

扩展性的话，目前整体布局是不支持有大改动的，但是内部子组件是开放的，同时也提供了一些行为的自定义接口，在默认行为不满足的情况下，进行扩展。

具体可能参考ReadMe的 [高级进阶](https://github.com/zhaoyang21cn/IMTUIkit_android#%E9%AB%98%E7%BA%A7%E8%BF%9B%E9%98%B6) 章节

**Comment by delayhsiao** [comment]
坐等ios版本的开放
目前整体布局的集成是不太可能集成的，毕竟应对不同的业务需求，可能界面上会有一些差异。但是子组件的开放表示很有兴趣，毕竟子组件的自行实现比较费力。
表示看好TUIkit的两端版本，如果可以的话，来个前端版本最棒了！
啥时候把前端的git开了，我来贡献代码鸭😁

**Comment by delayhsiao** [comment]
@zhaoyang21cn 时刻关注呢~ 一周过去啦~
